[Variables]
;Enter your latitude and longitude in degrees to get your weather from the API
;Get accurate coordinates from https://www.latlong.net/
latitude=40.8482
longitude=-73.8646


https://api.open-meteo.com/v1/forecast?latitude=40.8482&longitude=-73.8646&hourly=apparent_temperature&daily=weathercode,temperature_2m_max&current_weather=true&temperature_unit=fahrenheit&precipitation_unit=inch&timezone=auto
